receivers:
  hostmetrics:
    collection_interval: 60s
    scrapers:
      cpu:
      disk:
      filesystem:
      memory:
      network:
      load:
      paging:
      processes:
      system:

processors:
  batch:
  resource:
    attributes:
      - key: service.name
        value: my-service
        action: upsert
  resourcedetection:
    detectors: [env, system]
    system:
      hostname_sources: [os]

exporters:
  logging:
    loglevel: debug
  datadog:
    api:
      key: "your_hardcoded_datadog_api_key"
    site: "datadoghq.com"

service:
  pipelines:
    metrics:
      receivers: [hostmetrics]
      processors: [batch, resource, resourcedetection]
      exporters: [logging, datadog]
    traces:
      receivers: []
      processors: [batch, resource, resourcedetection]
      exporters: [logging, datadog]

