receivers:
  docker_stats:
    endpoint: unix:///var/run/docker.sock
    metrics:
      container.network.io.usage.rx_packets:
        enabled: true
      container.network.io.usage.tx_packets:
        enabled: true
      container.cpu.usage.system:
        enabled: true
      container.memory.rss:
        enabled: true
      container.blockio.io_serviced_recursive:
        enabled: true
      container.uptime:
        enabled: true
      container.memory.hierarchical_memory_limit:
        enabled: true

  hostmetrics:
    collection_interval: 60s
    scrapers:
      cpu:
      disk:
      filesystem:
      memory:
      network:
      load:
      paging:
      processes:
      system:

processors:
  batch:
    send_batch_max_size: 1000
    send_batch_size: 100
    timeout: 10s

  resource:
    attributes:
      - key: service.name
        value: my-service
        action: upsert

  resourcedetection:
    detectors: [system]

exporters:
  logging:
    loglevel: debug
  datadog:
    api:
      site: "datadoghq.com"
      key: "your_hardcoded_datadog_api_key"

service:
  pipelines:
    metrics:
      receivers: [docker_stats, hostmetrics]
      processors: [batch, resource, resourcedetection]
      exporters: [logging, datadog]
    traces:
      receivers: []
      processors: [batch, resource, resourcedetection]
      exporters: [logging, datadog]
