
services:
  datadog-agent:
    image: gcr.io/datadoghq/agent:latest
    environment:
      - DD_API_KEY=${DD_API_KEY}
      - DD_SITE=datadoghq.com
      - DD_ENV=swarm
      - DD_TAGS=owner:nostrich
      - DD_DOGSTATSD_NON_LOCAL_TRAFFIC=true
      - DD_DOCKER_LABELS_AS_TAGS=true
      - DD_DOCKER_ENV_AS_TAGS=true
      - DD_SYSTEM_PROBE_ENABLED=true
      - DD_PROCESS_AGENT_ENABLED=true
      - DD_APM_NON_LOCAL_TRAFFIC=true
      - DD_LOGS_ENABLED=true
      - DD_LOGS_CONFIG_CONTAINER_COLLECT_ALL=true
      - DD_CONTAINER_EXCLUDE="image:datadog/agent:latest"
      - DD_LOG_LEVEL=info
      - DD_REMOTE_CONFIGURATION_ENABLED=true
      - DD_LOGS_CONFIG_AUTO_MULTI_LINE_DETECTION=true
    volumes:
      - type: bind
        source: /var/run/docker.sock
        target: /var/run/docker.sock
        read_only: true
      - type: bind
        source: /var/lib/docker/containers
        target: /var/lib/docker/containers
        read_only: true
      - type: bind
        source: /proc
        target: /host/proc
        read_only: true
      - type: bind
        source: /sys/fs/cgroup
        target: /host/sys/fs/cgroup
        read_only: true
      - type: bind
        source: /sys/kernel/debug
        target: /sys/kernel/debug
      - type: bind
        source: /etc/passwd
        target: /etc/passwd
        read_only: true
      - type: volume
        source: datadog-run
        target: /opt/datadog-agent/run
    cap_add:
      - SYS_ADMIN
      - SYS_RESOURCE
      - SYS_PTRACE
      - NET_ADMIN
      - NET_BROADCAST
      - NET_RAW
      - IPC_LOCK
      - CHOWN
    security_opt:
      - apparmor:unconfined
    networks:
      - my-overlay-network
    deploy:
      mode: global
      restart_policy:
        condition: on-failure

volumes:
  datadog-run:

networks:
  my-overlay-network:
    driver: overlay
