version: '3.8'

services:
  nostr-relay-primary:
    image: bhartford419/nostr-rs-relay:pg_primary
    user: "100:100"
    ports:
      - target: 8080
        published: 8080
        protocol: tcp
        mode: host
    networks:
      - my-overlay-network
    deploy:
      mode: replicated
      replicas: 2
      placement:
        constraints: 
          - node.role == worker
          - node.labels.region == useast
      restart_policy:
        condition: on-failure

  nostr-relay-secondary:
    image: bhartford419/nostr-rs-relay:pg_replica
    user: "100:100"
    ports:
      - target: 8080
        published: 8081
        protocol: tcp
        mode: host
    networks:
      - my-overlay-network
    deploy:
      mode: replicated
      replicas: 2
      placement:
        constraints: 
          - node.role == worker
          - node.labels.region == asia
      restart_policy:
        condition: on-failure

  nginx-certbot:
    image: bhartford419/nginx-certbot:swarm
    environment:
      - DOMAIN=global.serverless-nostr.com
    ports:
      - target: 80
        published: 80
        protocol: tcp
        mode: host
      - target: 443
        published: 443
        protocol: tcp
        mode: host
    configs:
      - source: certs
        target: /etc/letsencrypt
        mode: 0444
      - source: certs-data
        target: /var/lib/letsencrypt
        mode: 0444
    networks:
      - my-overlay-network
    deploy:
      mode: replicated
      replicas: 2
      placement:
        constraints: [node.role == manager]
      restart_policy:
        condition: on-failure

networks:
  my-overlay-network:
    driver: overlay
    attachable: true

volumes:
  pgdata:

configs:
  certs:
    external: true
  certs-data:
    external: true
