version: '3.8'

services:
  nostr-relay:
    build:
      context: .
      dockerfile: Dockerfile
    user: "100:100"
    ports:
      - "8080:8080"
    volumes:
      - ./data:/usr/src/app/db
      - ./config.toml:/usr/src/app/config.toml:ro
      - ./logs:/usr/src/app/loggit status
    restart: unless-stopped
    deploy:
      mode: replicated
      replicas: 5
      restart_policy:
        condition: on-failure

networks:
  my-overlay-network:
    external: true
