version: '3.8'

services:
  nostr-relay:
    image: bhartford419/nostr-rs-relay:hardcode
    user: "100:100"
    ports:
      - target: 8080
        published: 8080
        protocol: tcp
        mode: host
    volumes:
      - ./data:/usr/src/app/db
      - ./config.toml:/usr/src/app/config.toml:ro
      - ./logs:/usr/src/app/log
    networks:
      - my-overlay-network
    deploy:
      mode: replicated
      replicas: 3
      placement:
        constraints: [node.role == worker]
      restart_policy:
        condition: on-failure

  nginx-certbot:
    image: bhartford419/nginx-certbot:swarm
    environment:
      - DOMAIN=swarm.serverless-nostr.com
    ports:
      - target: 80
        published: 80
        protocol: tcp
        mode: host
      - target: 443
        published: 443
        protocol: tcp
        mode: host
    networks:
      - my-overlay-network
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.role == manager]
      restart_policy:
        condition: on-failure

networks:
  my-overlay-network:
    driver: overlay
    attachable: true
