version: '3.8'

services:
  nostr-relay:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nostr-relay
    user: "100:100"
    ports:
      - "7000:8080"
    volumes:
      - ./data:/usr/src/app/db
      - ./config.toml:/usr/src/app/config.toml:ro
    restart: unless-stopped
